services:
  android:
    build:
      context: .
      args:
        - OPENJDK_VERSION=${OPENJDK_VERSION}
    ports:
      - "6080:6080" # noVNC web interface
      - "5901:5901" # VNC direct connection
    env_file:
      - .env
    volumes:
      - ./logs:/var/log/supervisor
    restart: "unless-stopped"
  redroid:
    image: redroid/redroid:16.0.0_64only-latest
    privileged: true
    ports:
      - "5555:5555"
    volumes:
      - ~/data11:/data
    restart: "unless-stopped" # 对应 --rm，容器停止时不保留
